### ISSUE TITLE
Elimizdeki Çeviriler

### ISSUE THREAD

**Issue by selcux** [gelis-tr-io/ceviriler#1]
Selamlar,

Daha önce yaptığımız çevirileri buraya eklemekte bir sakınca var mı?
Bilgilerin bir arada olması açısından aşağıdaki yazıyı eklemek isterim.

https://medium.com/turkce/cap-teoremi-nedir-49a23e6d2e10

**Comment by tarikguney** [comment]
Tabiki de ekleyebilirsiniz.
