### ISSUE TITLE
Çeviri Bilgileri

### ISSUE THREAD

**Issue by selcux** [gelis-tr-io/ceviriler#4]
Selamlar,

Çeviriler ana sayfasında 

> Çevirisi Tamamlanan Kaynağın Başlığı - Yazar - Varsa URL

kısmında tam olarak neyi yazmamız gerekiyor? Orjinal kaynağın Yazarı ve URLi mi? Yoksa çevirmeninkileri mi?

Ona göre yazının içinde orjinal kaynağa link verip vermeyeceğimi belirleyeceğim.

Kolay gelsin

**Comment by tarikguney** [comment]
Orijinal yazarin adi ve url. Eger yazar bir kurum ise o zaman kurumun adi. Mesela Mozilla, Oracle! Microsoft. Ceviri ile alakali kendine ait bilgileri ise ceviri klasorunde ki readme.md dosyasina koyabilirsin.Mesela aktif olarak calisan insanlarin isimleri Katki Saglayanlar basligi altinda listenebilir.
